name: $(SourceBranchName)-$(Date:yyyyMmdd)$(Rev:.r)

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - cicd/templates/steps-deploy-amazon-q.yaml
    - cicd/amazon-q-pipeline.yaml

    - cicd/infra-pipeline.yaml
    - cicd/templates/steps-deploy-tf.yaml
    - deploy
    - src

pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

parameters:
- name: environments
  type: object
  default: ['nonprod']
# - name: namespaces
#   type: object
#   default: ['dev']


variables:
 - template: variables/vars-global.yaml
stages:

- ${{ each env in parameters.environments }}:
  - stage: Deploy_${{ env }}
    displayName: Deploy ${{ env }} Storage Terraform
    jobs:
    - job: Deploy_Terraform
      displayName: Deploy terraform infrastructure
      #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      variables:
      - template: variables/vars-${{ env }}.yaml
      steps:
      - template: templates/steps-deploy-tf.yaml

  - stage: Deploy_amazon_q
    displayName: Deploy Amazon Q
    jobs:
      - job: Deploy_amazon_q
        displayName: Deploy Amazon Q
        # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))     
        steps:
        - template: templates/steps-deploy-amazonq-application.yaml
        - template: templates/steps-deploy-index.yaml
        - template: templates/steps-deploy-retriever.yaml
        - template: templates/steps-deploy-datasource.yaml
        - template: templates/steps-deploy-web-experience.yaml
        - template: templates/steps-deploy-update-web-experience.yaml
        